### ISSUE TITLE
balancer-v2-monorepo clean install/build doesn't pass unit tests.

### ISSUE THREAD

**Issue by scherrey** [balancer-labs/balancer-v2-monorepo#1986]
I've been trying to build a test environment with the main monorepo so I can develop contracts that interoperate for Balancer (this is for the Dynamo Protocol). Unfortunately I'm having no success confirming that I have a known good working Balancer V2 build. I follow the instructions from https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/README.md but most unit tests fail. I've reproduced the issue on two different Linux computers.

Is it intended that the master branch should compile & pass unit tests by doing nothing beyond what's in the README.md file? Here's a complete bash capture of my installation procedures. I also will attach a copy in a file, yarn_install.txt, and will attach another file that shows the unit test run, yarn_test.txt as it's too large to post inline here.

Please confirm my expectations are correct and let me know if I'm not doing something I should be.

Here's my environment:
```
uname -a
Linux squire 5.14.0-4mx-amd64 #1 SMP Debian 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux
```

Thanks! We're quite looking forward to integrating with Balancer's Pool/Vault ecosystem.

Not sure what the warnings that start with YN0007 refer to but they look potentially ominous. Since they never claim to be errors I presume this output is what I should expect to see for a correct build, yes? I've never used yarn before so I'm not at all familiar with this build environment. Appreciate any insights anyone can share.

```

scherrey@squire:~/projects/Dynamo
$ git clone --recurse-submodules https://github.com/balancer-labs/balancer-v2-monorepo.git
Cloning into 'balancer-v2-monorepo'...
remote: Enumerating objects: 30539, done.
remote: Counting objects: 100% (492/492), done.
remote: Compressing objects: 100% (218/218), done.
remote: Total 30539 (delta 306), reused 421 (delta 273), pack-reused 30047
Receiving objects: 100% (30539/30539), 68.39 MiB | 16.14 MiB/s, done.
Resolving deltas: 100% (22093/22093), done.
Updating files: 100% (1450/1450), done.
Submodule 'pvt/lib/forge-std' (https://github.com/foundry-rs/forge-std) registered for path 'pvt/lib/forge-std'
Cloning into '/home/scherrey/projects/Dynamo/balancer-v2-monorepo/pvt/lib/forge-std'...
remote: Enumerating objects: 1135, done.        
remote: Counting objects: 100% (504/504), done.        
remote: Compressing objects: 100% (179/179), done.        
remote: Total 1135 (delta 376), reused 398 (delta 311), pack-reused 631        
Receiving objects: 100% (1135/1135), 274.60 KiB | 2.25 MiB/s, done.
Resolving deltas: 100% (698/698), done.
Submodule path 'pvt/lib/forge-std': checked out 'f36dab24d63d1c1945a05ed375ce341d3c1a49ed'
Submodule 'lib/ds-test' (https://github.com/dapphub/ds-test) registered for path 'pvt/lib/forge-std/lib/ds-test'
Cloning into '/home/scherrey/projects/Dynamo/balancer-v2-monorepo/pvt/lib/forge-std/lib/ds-test'...
remote: Enumerating objects: 212, done.        
remote: Counting objects: 100% (70/70), done.        
remote: Compressing objects: 100% (27/27), done.        
remote: Total 212 (delta 47), reused 45 (delta 40), pack-reused 142        
Receiving objects: 100% (212/212), 54.11 KiB | 1.46 MiB/s, done.
Resolving deltas: 100% (86/86), done.
Submodule path 'pvt/lib/forge-std/lib/ds-test': checked out '9310e879db8ba3ea6d5c6489a579118fd264a3f5'
scherrey@squire:~/projects/Dynamo
$ nvm install 16.17.0
Downloading and installing node v16.17.0...
Downloading https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz...
##################################################################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.17.0 (npm v8.15.0)
scherrey@squire:~/projects/Dynamo
$ corepack enable
scherrey@squire:~/projects/Dynamo
$ corepack prepare yarn@stable --activate
Preparing yarn@stable for immediate activation...
scherrey@squire:~/projects/Dynamo
$ yarn --version
3.2.4
scherrey@squire:~/projects/Dynamo
$ cd balancer-v2-monorepo/
scherrey@squire:~/projects/Dynamo/balancer-v2-monorepo
$ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide @ethersproject/providers (p3b7db), requested by @balancer-labs/typechain
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide @ethersproject/providers (p6e2ee), requested by @typechain/ethers-v5
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide ethers (p0aa6e), requested by @balancer-labs/typechain
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide ethers (p8b50d), requested by @typechain/ethers-v5
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide tslib (p042b4), requested by @rollup/plugin-typescript
➤ YN0060: │ @balancer-labs/v2-distributors@workspace:pkg/distributors provides prettier (p170da) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-governance-scripts@workspace:pkg/governance-scripts provides prettier (pb68eb) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-interfaces@workspace:pkg/interfaces provides prettier (pd741e) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-liquidity-mining@workspace:pkg/liquidity-mining provides prettier (p0e51e) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-linear@workspace:pkg/pool-linear provides prettier (p47611) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-stable@workspace:pkg/pool-stable provides prettier (p409f8) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-utils@workspace:pkg/pool-utils provides prettier (p44467) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-weighted@workspace:pkg/pool-weighted provides prettier (p2c891) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-solidity-utils@workspace:pkg/solidity-utils provides prettier (p16ad1) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-standalone-utils@workspace:pkg/standalone-utils provides prettier (pd4501) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-vault@workspace:pkg/vault provides prettier (pb55d6) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0002: │ typechain@npm:3.0.0 doesn't provide typescript (p4ba7f), requested by ts-essentials
➤ YN0002: │ typechain@npm:5.1.1 doesn't provide typescript (p861d0), requested by ts-essentials
➤ YN0002: │ typechain@npm:5.1.2 doesn't provide typescript (p2a387), requested by ts-essentials
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 207ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-unparser@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:16.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:4.8.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2s 610ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ @nomicfoundation/solidity-analyzer-darwin-arm64@npm:0.1.0 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ @nomicfoundation/solidity-analyzer-darwin-x64@npm:0.1.0 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ @nomicfoundation/solidity-analyzer-freebsd-x64@npm:0.1.0 The platform linux is incompatible with this module, link skipped.
➤ YN0063: │ @nomicfoundation/solidity-analyzer-linux-arm64-gnu@npm:0.1.0 The CPU architecture x64 is incompatible with this module, link skipped.
➤ YN0063: │ @nomicfoundation/solidity-analyzer-linux-arm64-musl@npm:0.1.0 The CPU architecture x64 is incompatible with this module, link skipped.
➤ YN0062: │ @nomicfoundation/solidity-analyzer-win32-arm64-msvc@npm:0.1.0 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ @nomicfoundation/solidity-analyzer-win32-ia32-msvc@npm:0.1.0 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ @nomicfoundation/solidity-analyzer-win32-x64-msvc@npm:0.1.0 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ solidity-comments-darwin-arm64@npm:0.0.2 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ solidity-comments-darwin-x64@npm:0.0.2 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ solidity-comments-freebsd-x64@npm:0.0.2 The platform linux is incompatible with this module, link skipped.
➤ YN0063: │ solidity-comments-linux-arm64-gnu@npm:0.0.2 The CPU architecture x64 is incompatible with this module, link skipped.
➤ YN0063: │ solidity-comments-linux-arm64-musl@npm:0.0.2 The CPU architecture x64 is incompatible with this module, link skipped.
➤ YN0062: │ solidity-comments-win32-arm64-msvc@npm:0.0.2 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ solidity-comments-win32-ia32-msvc@npm:0.0.2 The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ solidity-comments-win32-x64-msvc@npm:0.0.2 The platform linux is incompatible with this module, link skipped.
➤ YN0007: │ keccak@npm:3.0.2 must be built because it never did before or the last one failed
➤ YN0007: │ nodemon@npm:2.0.7 must be built because it never did before or the last one failed
➤ YN0007: │ keccak@npm:3.0.1 must be built because it never did before or the last one failed
➤ YN0007: │ secp256k1@npm:4.0.2 must be built because it never did before or the last one failed
➤ YN0007: │ postinstall-postinstall@npm:2.1.0 must be built because it never did before or the last one failed
➤ YN0007: │ classic-level@npm:1.2.0 must be built because it never did before or the last one failed
➤ YN0007: │ web3@npm:1.2.11 must be built because it never did before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.12.0 must be built because it never did before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.3 must be built because it never did before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.5 must be built because it never did before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 2m 15s
➤ YN0000: Done with warnings in 2m 18s
scherrey@squire:~/projects/Dynamo/balancer-v2-monorepo
$ yarn build | tee yarn_build.txt
➤ YN0000: [@balancer-labs/v2-deployments]: ../../pvt/common/setupTests.ts(7,32): error TS2307: Cannot find module '@balancer-labs/balancer-js' or its corresponding type declarations.
➤ YN0000: [@balancer-labs/balancer-js]: 
➤ YN0000: [@balancer-labs/balancer-js]: src/index.ts → dist/index.umd.js, dist/index.js, dist/index.esm.js...
➤ YN0000: [@balancer-labs/balancer-js]: (!) Missing global variable names
➤ YN0000: [@balancer-labs/balancer-js]: Use output.globals to specify browser global variable names corresponding to external modules
➤ YN0000: [@balancer-labs/balancer-js]: @ethersproject/abi (guessing 'abi')
➤ YN0000: [@balancer-labs/balancer-js]: @ethersproject/constants (guessing 'constants')
➤ YN0000: [@balancer-labs/balancer-js]: @ethersproject/bignumber (guessing 'bignumber')
➤ YN0000: [@balancer-labs/balancer-js]: @ethersproject/bytes (guessing 'bytes')
➤ YN0000: [@balancer-labs/balancer-js]: @ethersproject/abstract-signer (guessing 'abstractSigner')
➤ YN0000: [@balancer-labs/balancer-js]: @ethersproject/address (guessing 'address')
➤ YN0000: [@balancer-labs/balancer-js]: created dist/index.umd.js, dist/index.js, dist/index.esm.js in 4.3s
➤ YN0000: [@balancer-labs/balancer-js]: 
➤ YN0000: [@balancer-labs/balancer-js]: src/index.ts → dist/index.d.ts...
➤ YN0000: [@balancer-labs/balancer-js]: created dist/index.d.ts in 3.4s
➤ YN0000: [@balancer-labs/v2-distributors]: Compiled 20 Solidity files successfully
➤ YN0000: [@balancer-labs/v2-interfaces]: Compiled 72 Solidity files successfully
➤ YN0000: [@balancer-labs/v2-governance-scripts]: Compiled 24 Solidity files successfully
➤ YN0000: [@balancer-labs/v2-liquidity-mining]: Compiled 86 Solidity files successfully
➤ YN0000: [@balancer-labs/v2-liquidity-mining]: Downloading compiler 0.3.3
➤ YN0000: [@balancer-labs/v2-liquidity-mining]: Downloading compiler 0.3.1
➤ YN0000: [@balancer-labs/v2-liquidity-mining]: Vyper compilation finished successfully
scherrey@squire:~/projects/Dynamo/balancer-v2-monorepo

```

**Comment by scherrey** [comment]
[yarn_install.txt](https://github.com/balancer-labs/balancer-v2-monorepo/files/9948538/yarn_install.txt)
[yarn_test.txt](https://github.com/balancer-labs/balancer-v2-monorepo/files/9948539/yarn_test.txt)

**Comment by EndymionJkb** [comment]
It should certainly work out of the box, yes!

The issue is likely your Node version. Our configuration (hardhat, etc.) only works with Node 14.x. We'll add that to the docs.

**Comment by scherrey** [comment]
OK we were able to get it to mostly pass by using node v.14.21.1 and yarn v.2.4.1. All the tests pass as expected except for 35 "fork tests" which seem to require some other environment to be setup in order to pass. Any advice on this?

Here's an example of the first failure. I've attached a file that has them all here.
```
113 ➤ YN0000: [@balancer-labs/v2-deployments]:   1) NoProtocolFeeLiquidityBootstrappingPoolFactory
 114 ➤ YN0000: [@balancer-labs/v2-deployments]:        "before all" hook: setup fork test for "deploy a liquidity bootstrapping pool":
 115 ➤ YN0000: [@balancer-labs/v2-deployments]:      Error: Could not find a config for network mainnet to be forked
 116 ➤ YN0000: [@balancer-labs/v2-deployments]:       at Context.<anonymous> (src/forkTests.ts:28:36)
 117 ➤ YN0000: [@balancer-labs/v2-deployments]:       at processImmediate (internal/timers.js:464:21)
```

[yarn_test_fail.txt](https://github.com/balancer-labs/balancer-v2-monorepo/files/9959315/yarn_test_fail.txt)

**Comment by jubeira** [comment]
Hi @scherrey, were you able to get everything up and running?

Can this issue be closed?

**Comment by scherrey** [comment]
Oh sorry - yes this works now. I didn't realize it was waiting for me. Closed.
